name: Deploy to Production

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H profullstack >> ~/.ssh/known_hosts
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync
          
      - name: Deploy to server
        run: |
          # Make deploy script executable
          chmod +x ./bin/deploy.sh
          
          # Print debug info
          echo "Current directory: $(pwd)"
          echo "Files in bin directory:"
          ls -la ./bin
          
          # Run deploy script
          ./bin/deploy.sh
          
          # Run test script to verify deployment
          echo "Running test script on remote server..."
          ssh profullstack "cd $DEPLOY_REMOTE_DIR && chmod +x bin/test-github-actions.sh && ./bin/test-github-actions.sh"
        env:
          DEPLOY_REMOTE_HOST: profullstack
          DEPLOY_REMOTE_DIR: www/profullstack.com/pdf
          INSTALL_SERVICE: true